export interface Movie {
  title: string;
  year: number;
  rt?: number | null;
}

export type Tier = "high" | "mid" | "low";

export interface PoolEntry extends Movie {
  tier: Tier;
}

// ~650 movies across three tiers for maximum variety
export const MOVIE_POOL: PoolEntry[] = [
  // ===== HIGH (expected 90-100) =====
  { title: "Parasite", year: 2019, tier: "high" },
  { title: "Mad Max: Fury Road", year: 2015, tier: "high" },
  { title: "Get Out", year: 2017, tier: "high" },
  { title: "Moonlight", year: 2016, tier: "high" },
  { title: "Hereditary", year: 2018, tier: "high" },
  { title: "Knives Out", year: 2019, tier: "high" },
  { title: "The Witch", year: 2015, tier: "high" },
  { title: "Arrival", year: 2016, tier: "high" },
  { title: "Dunkirk", year: 2017, tier: "high" },
  { title: "Whiplash", year: 2014, tier: "high" },
  { title: "Birdman", year: 2014, tier: "high" },
  { title: "Her", year: 2013, tier: "high" },
  { title: "Gravity", year: 2013, tier: "high" },
  { title: "12 Years a Slave", year: 2013, tier: "high" },
  { title: "The Social Network", year: 2010, tier: "high" },
  { title: "Toy Story 3", year: 2010, tier: "high" },
  { title: "Inception", year: 2010, tier: "high" },
  { title: "Drive", year: 2011, tier: "high" },
  { title: "Moneyball", year: 2011, tier: "high" },
  { title: "The Artist", year: 2011, tier: "high" },
  { title: "Silver Linings Playbook", year: 2012, tier: "high" },
  { title: "Argo", year: 2012, tier: "high" },
  { title: "Looper", year: 2012, tier: "high" },
  { title: "Moonrise Kingdom", year: 2012, tier: "high" },
  { title: "Boyhood", year: 2014, tier: "high" },
  { title: "Gone Girl", year: 2014, tier: "high" },
  { title: "Inside Out", year: 2015, tier: "high" },
  { title: "The Revenant", year: 2015, tier: "high" },
  { title: "Black Swan", year: 2010, tier: "high" },
  { title: "True Grit", year: 2010, tier: "high" },
  { title: "Blade Runner 2049", year: 2017, tier: "high" },
  { title: "Spider-Man: Into the Spider-Verse", year: 2018, tier: "high" },
  { title: "Black Panther", year: 2018, tier: "high" },
  { title: "Marriage Story", year: 2019, tier: "high" },
  { title: "Once Upon a Time in Hollywood", year: 2019, tier: "high" },
  { title: "Midsommar", year: 2019, tier: "high" },
  { title: "Barbie", year: 2023, tier: "high" },
  { title: "Oppenheimer", year: 2023, tier: "high" },
  { title: "Past Lives", year: 2023, tier: "high" },
  { title: "The Zone of Interest", year: 2023, tier: "high" },
  { title: "Poor Things", year: 2023, tier: "high" },
  { title: "Killers of the Flower Moon", year: 2023, tier: "high" },
  { title: "Dune: Part Two", year: 2024, tier: "high" },
  { title: "Civil War", year: 2024, tier: "high" },
  { title: "Alien: Romulus", year: 2024, tier: "high" },
  { title: "Furiosa", year: 2024, tier: "high" },
  { title: "Nightcrawler", year: 2014, tier: "high" },
  { title: "The Grand Budapest Hotel", year: 2014, tier: "high" },
  { title: "Django Unchained", year: 2012, tier: "high" },
  { title: "Zero Dark Thirty", year: 2012, tier: "high" },
  { title: "Midnight in Paris", year: 2011, tier: "high" },
  { title: "The King's Speech", year: 2010, tier: "high" },
  // New high entries
  { title: "The Dark Knight", year: 2008, tier: "high" },
  { title: "WALL-E", year: 2008, tier: "high" },
  { title: "Slumdog Millionaire", year: 2008, tier: "high" },
  { title: "Up", year: 2009, tier: "high" },
  { title: "The Hurt Locker", year: 2009, tier: "high" },
  { title: "District 9", year: 2009, tier: "high" },
  { title: "Inglourious Basterds", year: 2009, tier: "high" },
  { title: "Star Trek", year: 2009, tier: "high" },
  { title: "No Country for Old Men", year: 2007, tier: "high" },
  { title: "There Will Be Blood", year: 2007, tier: "high" },
  { title: "Ratatouille", year: 2007, tier: "high" },
  { title: "Juno", year: 2007, tier: "high" },
  { title: "The Departed", year: 2006, tier: "high" },
  { title: "Pan's Labyrinth", year: 2006, tier: "high" },
  { title: "Little Miss Sunshine", year: 2006, tier: "high" },
  { title: "Children of Men", year: 2006, tier: "high" },
  { title: "The Incredibles", year: 2004, tier: "high" },
  { title: "Eternal Sunshine of the Spotless Mind", year: 2004, tier: "high" },
  { title: "Finding Nemo", year: 2003, tier: "high" },
  { title: "Lost in Translation", year: 2003, tier: "high" },
  { title: "The Lord of the Rings: The Return of the King", year: 2003, tier: "high" },
  { title: "City of God", year: 2002, tier: "high" },
  { title: "Spirited Away", year: 2001, tier: "high" },
  { title: "Amelie", year: 2001, tier: "high" },
  { title: "The Lord of the Rings: The Fellowship of the Ring", year: 2001, tier: "high" },
  { title: "Gladiator", year: 2000, tier: "high" },
  { title: "Memento", year: 2000, tier: "high" },
  { title: "Almost Famous", year: 2000, tier: "high" },
  { title: "The Matrix", year: 1999, tier: "high" },
  { title: "American Beauty", year: 1999, tier: "high" },
  { title: "Fight Club", year: 1999, tier: "high" },
  { title: "The Sixth Sense", year: 1999, tier: "high" },
  { title: "Saving Private Ryan", year: 1998, tier: "high" },
  { title: "The Truman Show", year: 1998, tier: "high" },
  { title: "Good Will Hunting", year: 1997, tier: "high" },
  { title: "Titanic", year: 1997, tier: "high" },
  { title: "L.A. Confidential", year: 1997, tier: "high" },
  { title: "Fargo", year: 1996, tier: "high" },
  { title: "Toy Story", year: 1995, tier: "high" },
  { title: "Se7en", year: 1995, tier: "high" },
  { title: "The Shawshank Redemption", year: 1994, tier: "high" },
  { title: "Pulp Fiction", year: 1994, tier: "high" },
  { title: "Forrest Gump", year: 1994, tier: "high" },
  { title: "The Lion King", year: 1994, tier: "high" },
  { title: "Schindler's List", year: 1993, tier: "high" },
  { title: "Jurassic Park", year: 1993, tier: "high" },
  { title: "Unforgiven", year: 1992, tier: "high" },
  { title: "The Silence of the Lambs", year: 1991, tier: "high" },
  { title: "Goodfellas", year: 1990, tier: "high" },
  { title: "Inside Out 2", year: 2024, tier: "high" },
  { title: "The Wild Robot", year: 2024, tier: "high" },
  { title: "Anora", year: 2024, tier: "high" },
  { title: "A Real Pain", year: 2024, tier: "high" },
  { title: "The Brutalist", year: 2024, tier: "high" },
  { title: "Conclave", year: 2024, tier: "high" },
  { title: "A Quiet Place: Day One", year: 2024, tier: "high" },
  { title: "The Holdovers", year: 2023, tier: "high" },
  { title: "American Fiction", year: 2023, tier: "high" },
  { title: "Anatomy of a Fall", year: 2023, tier: "high" },
  { title: "The Banshees of Inisherin", year: 2022, tier: "high" },
  { title: "Everything Everywhere All at Once", year: 2022, tier: "high" },
  { title: "Top Gun: Maverick", year: 2022, tier: "high" },
  { title: "Tar", year: 2022, tier: "high" },
  { title: "The Fabelmans", year: 2022, tier: "high" },
  { title: "Aftersun", year: 2022, tier: "high" },
  { title: "Nope", year: 2022, tier: "high" },
  { title: "The Batman", year: 2022, tier: "high" },
  { title: "Glass Onion", year: 2022, tier: "high" },
  { title: "Nomadland", year: 2020, tier: "high" },
  { title: "Promising Young Woman", year: 2020, tier: "high" },
  { title: "Minari", year: 2020, tier: "high" },
  { title: "Sound of Metal", year: 2019, tier: "high" },
  { title: "1917", year: 2019, tier: "high" },
  { title: "Jojo Rabbit", year: 2019, tier: "high" },
  { title: "Uncut Gems", year: 2019, tier: "high" },
  { title: "The Lighthouse", year: 2019, tier: "high" },
  { title: "Little Women", year: 2019, tier: "high" },
  { title: "Booksmart", year: 2019, tier: "high" },
  { title: "Us", year: 2019, tier: "high" },
  { title: "A Quiet Place", year: 2018, tier: "high" },
  { title: "Eighth Grade", year: 2018, tier: "high" },
  { title: "Roma", year: 2018, tier: "high" },
  { title: "The Favourite", year: 2018, tier: "high" },
  { title: "Mission: Impossible - Fallout", year: 2018, tier: "high" },
  { title: "Paddington 2", year: 2017, tier: "high" },
  { title: "Lady Bird", year: 2017, tier: "high" },
  { title: "The Shape of Water", year: 2017, tier: "high" },
  { title: "Three Billboards Outside Ebbing, Missouri", year: 2017, tier: "high" },
  { title: "Coco", year: 2017, tier: "high" },
  { title: "Baby Driver", year: 2017, tier: "high" },
  { title: "La La Land", year: 2016, tier: "high" },
  { title: "Manchester by the Sea", year: 2016, tier: "high" },
  { title: "Hell or High Water", year: 2016, tier: "high" },
  { title: "Zootopia", year: 2016, tier: "high" },
  { title: "Spotlight", year: 2015, tier: "high" },
  { title: "Room", year: 2015, tier: "high" },
  { title: "Ex Machina", year: 2014, tier: "high" },
  { title: "Selma", year: 2014, tier: "high" },
  { title: "The Lego Movie", year: 2014, tier: "high" },
  { title: "Short Term 12", year: 2013, tier: "high" },
  { title: "Before Midnight", year: 2013, tier: "high" },
  { title: "Captain Phillips", year: 2013, tier: "high" },
  { title: "Mud", year: 2012, tier: "high" },
  { title: "The Perks of Being a Wallflower", year: 2012, tier: "high" },
  { title: "Beasts of the Southern Wild", year: 2012, tier: "high" },
  { title: "The Descendants", year: 2011, tier: "high" },
  { title: "Bridesmaids", year: 2011, tier: "high" },
  { title: "Hugo", year: 2011, tier: "high" },
  { title: "How to Train Your Dragon", year: 2010, tier: "high" },
  { title: "Scott Pilgrim vs. the World", year: 2010, tier: "high" },
  { title: "Winter's Bone", year: 2010, tier: "high" },
  { title: "Coraline", year: 2009, tier: "high" },
  { title: "Fantastic Mr. Fox", year: 2009, tier: "high" },
  { title: "An Education", year: 2009, tier: "high" },
  { title: "In Bruges", year: 2008, tier: "high" },
  { title: "Iron Man", year: 2008, tier: "high" },
  { title: "Superbad", year: 2007, tier: "high" },
  { title: "Hot Fuzz", year: 2007, tier: "high" },
  { title: "Zodiac", year: 2007, tier: "high" },
  { title: "Persepolis", year: 2007, tier: "high" },
  { title: "The Lives of Others", year: 2006, tier: "high" },
  { title: "Casino Royale", year: 2006, tier: "high" },
  { title: "The Prestige", year: 2006, tier: "high" },
  { title: "Brokeback Mountain", year: 2005, tier: "high" },
  { title: "Batman Begins", year: 2005, tier: "high" },
  { title: "Crash", year: 2004, tier: "high" },
  { title: "Kill Bill: Volume 1", year: 2003, tier: "high" },
  { title: "28 Days Later", year: 2002, tier: "high" },
  { title: "Catch Me If You Can", year: 2002, tier: "high" },
  { title: "Monsters, Inc.", year: 2001, tier: "high" },
  { title: "Shrek", year: 2001, tier: "high" },
  { title: "Requiem for a Dream", year: 2000, tier: "high" },
  { title: "Crouching Tiger, Hidden Dragon", year: 2000, tier: "high" },
  { title: "O Brother, Where Art Thou?", year: 2000, tier: "high" },
  { title: "Toy Story 2", year: 1999, tier: "high" },
  { title: "The Iron Giant", year: 1999, tier: "high" },
  { title: "Being John Malkovich", year: 1999, tier: "high" },
  { title: "Rear Window", year: 1954, tier: "high" },
  { title: "Psycho", year: 1960, tier: "high" },
  { title: "2001: A Space Odyssey", year: 1968, tier: "high" },
  { title: "The Godfather", year: 1972, tier: "high" },
  { title: "Chinatown", year: 1974, tier: "high" },
  { title: "Jaws", year: 1975, tier: "high" },
  { title: "Alien", year: 1979, tier: "high" },
  { title: "Aliens", year: 1986, tier: "high" },
  { title: "The Princess Bride", year: 1987, tier: "high" },
  { title: "Die Hard", year: 1988, tier: "high" },
  { title: "Do the Right Thing", year: 1989, tier: "high" },
  { title: "Terminator 2: Judgment Day", year: 1991, tier: "high" },
  { title: "Groundhog Day", year: 1993, tier: "high" },
  { title: "Run Lola Run", year: 1998, tier: "high" },
  { title: "The Thin Red Line", year: 1998, tier: "high" },
  { title: "Trainspotting", year: 1996, tier: "high" },
  { title: "Heat", year: 1995, tier: "high" },
  { title: "12 Monkeys", year: 1995, tier: "high" },
  { title: "The Usual Suspects", year: 1995, tier: "high" },
  { title: "Apollo 13", year: 1995, tier: "high" },
  { title: "Braveheart", year: 1995, tier: "high" },
  { title: "Reservoir Dogs", year: 1992, tier: "high" },
  { title: "Aladdin", year: 1992, tier: "high" },
  { title: "Beauty and the Beast", year: 1991, tier: "high" },
  { title: "Edward Scissorhands", year: 1990, tier: "high" },
  { title: "Back to the Future", year: 1985, tier: "high" },
  { title: "E.T. the Extra-Terrestrial", year: 1982, tier: "high" },
  { title: "Raiders of the Lost Ark", year: 1981, tier: "high" },
  // Classics (1920s-1970s)
  { title: "The Cabinet of Dr. Caligari", year: 1920, tier: "high" },
  { title: "Nosferatu", year: 1922, tier: "high" },
  { title: "The General", year: 1926, tier: "high" },
  { title: "Metropolis", year: 1927, tier: "high" },
  { title: "M", year: 1931, tier: "high" },
  { title: "King Kong", year: 1933, tier: "high" },
  { title: "Modern Times", year: 1936, tier: "high" },
  { title: "The Wizard of Oz", year: 1939, tier: "high" },
  { title: "Gone with the Wind", year: 1939, tier: "high" },
  { title: "Citizen Kane", year: 1941, tier: "high" },
  { title: "Casablanca", year: 1942, tier: "high" },
  { title: "Double Indemnity", year: 1944, tier: "high" },
  { title: "It's a Wonderful Life", year: 1946, tier: "high" },
  { title: "The Third Man", year: 1949, tier: "high" },
  { title: "Sunset Boulevard", year: 1950, tier: "high" },
  { title: "Singin' in the Rain", year: 1952, tier: "high" },
  { title: "12 Angry Men", year: 1957, tier: "high" },
  { title: "Vertigo", year: 1958, tier: "high" },
  { title: "North by Northwest", year: 1959, tier: "high" },
  { title: "Some Like It Hot", year: 1959, tier: "high" },
  { title: "The Apartment", year: 1960, tier: "high" },
  { title: "Lawrence of Arabia", year: 1962, tier: "high" },
  { title: "To Kill a Mockingbird", year: 1962, tier: "high" },
  { title: "Dr. Strangelove", year: 1964, tier: "high" },
  { title: "The Good, the Bad and the Ugly", year: 1966, tier: "high" },
  { title: "Bonnie and Clyde", year: 1967, tier: "high" },
  { title: "The Graduate", year: 1967, tier: "high" },
  { title: "Night of the Living Dead", year: 1968, tier: "high" },
  { title: "Butch Cassidy and the Sundance Kid", year: 1969, tier: "high" },
  { title: "The French Connection", year: 1971, tier: "high" },
  { title: "A Clockwork Orange", year: 1971, tier: "high" },
  { title: "The Exorcist", year: 1973, tier: "high" },
  { title: "The Sting", year: 1973, tier: "high" },
  { title: "Blazing Saddles", year: 1974, tier: "high" },
  { title: "One Flew Over the Cuckoo's Nest", year: 1975, tier: "high" },
  { title: "Monty Python and the Holy Grail", year: 1975, tier: "high" },
  { title: "Taxi Driver", year: 1976, tier: "high" },
  { title: "Rocky", year: 1976, tier: "high" },
  { title: "Annie Hall", year: 1977, tier: "high" },
  { title: "Star Wars", year: 1977, tier: "high" },
  { title: "Close Encounters of the Third Kind", year: 1977, tier: "high" },
  { title: "Halloween", year: 1978, tier: "high" },
  { title: "Superman", year: 1978, tier: "high" },
  { title: "Apocalypse Now", year: 1979, tier: "high" },

  // ===== MID (expected 50-89) =====
  { title: "Joker", year: 2019, tier: "mid" },
  { title: "The Wolf of Wall Street", year: 2013, tier: "mid" },
  { title: "Thor: Ragnarok", year: 2017, tier: "mid" },
  { title: "Avengers: Endgame", year: 2019, tier: "mid" },
  { title: "Doctor Strange", year: 2016, tier: "mid" },
  { title: "Ant-Man", year: 2015, tier: "mid" },
  { title: "Jungle Cruise", year: 2021, tier: "mid" },
  { title: "Blonde", year: 2022, tier: "mid" },
  { title: "Don't Worry Darling", year: 2022, tier: "mid" },
  { title: "Babylon", year: 2022, tier: "mid" },
  { title: "Napoleon", year: 2023, tier: "mid" },
  { title: "Ferrari", year: 2023, tier: "mid" },
  { title: "Ticket to Paradise", year: 2022, tier: "mid" },
  { title: "Indiana Jones and the Dial of Destiny", year: 2023, tier: "mid" },
  { title: "Twisters", year: 2024, tier: "mid" },
  { title: "Longlegs", year: 2024, tier: "mid" },
  { title: "The Beekeeper", year: 2024, tier: "mid" },
  { title: "Halloween Ends", year: 2022, tier: "mid" },
  { title: "Lightyear", year: 2022, tier: "mid" },
  { title: "Pinocchio", year: 2022, tier: "mid" },
  { title: "Strange World", year: 2022, tier: "mid" },
  { title: "Chaos Walking", year: 2021, tier: "mid" },
  { title: "The Kissing Booth 3", year: 2021, tier: "mid" },
  { title: "Iron Man 2", year: 2010, tier: "mid" },
  { title: "The Tree of Life", year: 2011, tier: "mid" },
  { title: "Tinker Tailor Soldier Spy", year: 2011, tier: "mid" },
  { title: "Life of Pi", year: 2012, tier: "mid" },
  { title: "The Imitation Game", year: 2014, tier: "mid" },
  { title: "Foxcatcher", year: 2014, tier: "mid" },
  { title: "The Mummy", year: 2017, tier: "mid" },
  { title: "Men in Black International", year: 2019, tier: "mid" },
  { title: "Wish", year: 2023, tier: "mid" },
  { title: "The Flash", year: 2023, tier: "mid" },
  { title: "Trap", year: 2024, tier: "mid" },
  { title: "Argylle", year: 2024, tier: "mid" },
  // New mid entries
  { title: "Interstellar", year: 2014, tier: "mid" },
  { title: "The Avengers", year: 2012, tier: "mid" },
  { title: "Guardians of the Galaxy", year: 2014, tier: "mid" },
  { title: "Captain America: The Winter Soldier", year: 2014, tier: "mid" },
  { title: "Avengers: Infinity War", year: 2018, tier: "mid" },
  { title: "Spider-Man: Homecoming", year: 2017, tier: "mid" },
  { title: "Spider-Man: No Way Home", year: 2021, tier: "mid" },
  { title: "Wonder Woman", year: 2017, tier: "mid" },
  { title: "Logan", year: 2017, tier: "mid" },
  { title: "Deadpool", year: 2016, tier: "mid" },
  { title: "Deadpool 2", year: 2018, tier: "mid" },
  { title: "Shang-Chi and the Legend of the Ten Rings", year: 2021, tier: "mid" },
  { title: "Eternals", year: 2021, tier: "mid" },
  { title: "Black Widow", year: 2021, tier: "mid" },
  { title: "No Time to Die", year: 2021, tier: "mid" },
  { title: "The Suicide Squad", year: 2021, tier: "mid" },
  { title: "Venom", year: 2018, tier: "mid" },
  { title: "Venom: Let There Be Carnage", year: 2021, tier: "mid" },
  { title: "Aquaman", year: 2018, tier: "mid" },
  { title: "Justice League", year: 2017, tier: "mid" },
  { title: "Guardians of the Galaxy Vol. 2", year: 2017, tier: "mid" },
  { title: "Captain America: Civil War", year: 2016, tier: "mid" },
  { title: "Star Wars: The Force Awakens", year: 2015, tier: "mid" },
  { title: "Star Wars: The Last Jedi", year: 2017, tier: "mid" },
  { title: "Rogue One", year: 2016, tier: "mid" },
  { title: "Star Wars: The Rise of Skywalker", year: 2019, tier: "mid" },
  { title: "Jurassic World", year: 2015, tier: "mid" },
  { title: "Jurassic World: Fallen Kingdom", year: 2018, tier: "mid" },
  { title: "Ready Player One", year: 2018, tier: "mid" },
  { title: "The Greatest Showman", year: 2017, tier: "mid" },
  { title: "Bohemian Rhapsody", year: 2018, tier: "mid" },
  { title: "A Star Is Born", year: 2018, tier: "mid" },
  { title: "Crazy Rich Asians", year: 2018, tier: "mid" },
  { title: "Ocean's 8", year: 2018, tier: "mid" },
  { title: "Glass", year: 2019, tier: "mid" },
  { title: "It Chapter Two", year: 2019, tier: "mid" },
  { title: "Ford v Ferrari", year: 2019, tier: "mid" },
  { title: "The Irishman", year: 2019, tier: "mid" },
  { title: "Tenet", year: 2020, tier: "mid" },
  { title: "Soul", year: 2020, tier: "mid" },
  { title: "The Invisible Man", year: 2020, tier: "mid" },
  { title: "Birds of Prey", year: 2020, tier: "mid" },
  { title: "Dune", year: 2021, tier: "mid" },
  { title: "Free Guy", year: 2021, tier: "mid" },
  { title: "The French Dispatch", year: 2021, tier: "mid" },
  { title: "West Side Story", year: 2021, tier: "mid" },
  { title: "The Power of the Dog", year: 2021, tier: "mid" },
  { title: "Don't Look Up", year: 2021, tier: "mid" },
  { title: "Encanto", year: 2021, tier: "mid" },
  { title: "The Northman", year: 2022, tier: "mid" },
  { title: "Black Adam", year: 2022, tier: "mid" },
  { title: "Bullet Train", year: 2022, tier: "mid" },
  { title: "Elvis", year: 2022, tier: "mid" },
  { title: "The Menu", year: 2022, tier: "mid" },
  { title: "Avatar: The Way of Water", year: 2022, tier: "mid" },
  { title: "Black Panther: Wakanda Forever", year: 2022, tier: "mid" },
  { title: "Doctor Strange in the Multiverse of Madness", year: 2022, tier: "mid" },
  { title: "Thor: Love and Thunder", year: 2022, tier: "mid" },
  { title: "Puss in Boots: The Last Wish", year: 2022, tier: "mid" },
  { title: "Wonka", year: 2023, tier: "mid" },
  { title: "Guardians of the Galaxy Vol. 3", year: 2023, tier: "mid" },
  { title: "John Wick: Chapter 4", year: 2023, tier: "mid" },
  { title: "Elemental", year: 2023, tier: "mid" },
  { title: "The Super Mario Bros. Movie", year: 2023, tier: "mid" },
  { title: "Spider-Man: Across the Spider-Verse", year: 2023, tier: "mid" },
  { title: "Mission: Impossible - Dead Reckoning", year: 2023, tier: "mid" },
  { title: "Saltburn", year: 2023, tier: "mid" },
  { title: "The Hunger Games: The Ballad of Songbirds and Snakes", year: 2023, tier: "mid" },
  { title: "Asteroid City", year: 2023, tier: "mid" },
  { title: "The Creator", year: 2023, tier: "mid" },
  { title: "Anyone But You", year: 2023, tier: "mid" },
  { title: "Beetlejuice Beetlejuice", year: 2024, tier: "mid" },
  { title: "Deadpool and Wolverine", year: 2024, tier: "mid" },
  { title: "Gladiator II", year: 2024, tier: "mid" },
  { title: "Wicked", year: 2024, tier: "mid" },
  { title: "Moana 2", year: 2024, tier: "mid" },
  { title: "Despicable Me 4", year: 2024, tier: "mid" },
  { title: "Kingdom of the Planet of the Apes", year: 2024, tier: "mid" },
  { title: "Nosferatu", year: 2024, tier: "mid" },
  { title: "It Ends with Us", year: 2024, tier: "mid" },
  { title: "Fly Me to the Moon", year: 2024, tier: "mid" },
  { title: "The Garfield Movie", year: 2024, tier: "mid" },
  { title: "Kung Fu Panda 4", year: 2024, tier: "mid" },
  { title: "Abigail", year: 2024, tier: "mid" },
  { title: "The Dark Knight Rises", year: 2012, tier: "mid" },
  { title: "Skyfall", year: 2012, tier: "mid" },
  { title: "The Hunger Games", year: 2012, tier: "mid" },
  { title: "Prometheus", year: 2012, tier: "mid" },
  { title: "Les Miserables", year: 2012, tier: "mid" },
  { title: "The Great Gatsby", year: 2013, tier: "mid" },
  { title: "Pacific Rim", year: 2013, tier: "mid" },
  { title: "Frozen", year: 2013, tier: "mid" },
  { title: "Spectre", year: 2015, tier: "mid" },
  { title: "The Martian", year: 2015, tier: "mid" },
  { title: "Sicario", year: 2015, tier: "mid" },
  { title: "Creed", year: 2015, tier: "mid" },
  { title: "The Hateful Eight", year: 2015, tier: "mid" },
  { title: "Bridge of Spies", year: 2015, tier: "mid" },
  { title: "Kingsman: The Secret Service", year: 2014, tier: "mid" },
  { title: "John Wick", year: 2014, tier: "mid" },
  { title: "Dawn of the Planet of the Apes", year: 2014, tier: "mid" },
  { title: "Edge of Tomorrow", year: 2014, tier: "mid" },
  { title: "X-Men: Days of Future Past", year: 2014, tier: "mid" },
  { title: "The Hobbit: An Unexpected Journey", year: 2012, tier: "mid" },
  { title: "Ted", year: 2012, tier: "mid" },
  { title: "The Hunger Games: Catching Fire", year: 2013, tier: "mid" },
  { title: "Iron Man 3", year: 2013, tier: "mid" },
  { title: "American Hustle", year: 2013, tier: "mid" },
  { title: "Now You See Me", year: 2013, tier: "mid" },
  { title: "Elysium", year: 2013, tier: "mid" },
  { title: "The Maze Runner", year: 2014, tier: "mid" },
  { title: "The Conjuring", year: 2013, tier: "mid" },
  { title: "Avatar", year: 2009, tier: "mid" },
  { title: "Sherlock Holmes", year: 2009, tier: "mid" },
  { title: "Zombieland", year: 2009, tier: "mid" },
  { title: "The Hangover", year: 2009, tier: "mid" },
  { title: "Kick-Ass", year: 2010, tier: "mid" },
  { title: "Shutter Island", year: 2010, tier: "mid" },
  { title: "The Town", year: 2010, tier: "mid" },
  { title: "Tangled", year: 2010, tier: "mid" },
  { title: "Tron: Legacy", year: 2010, tier: "mid" },
  { title: "Mission: Impossible - Ghost Protocol", year: 2011, tier: "mid" },
  { title: "Rise of the Planet of the Apes", year: 2011, tier: "mid" },
  { title: "X-Men: First Class", year: 2011, tier: "mid" },
  { title: "The Help", year: 2011, tier: "mid" },
  { title: "Super 8", year: 2011, tier: "mid" },
  { title: "Rango", year: 2011, tier: "mid" },
  { title: "I Am Legend", year: 2007, tier: "mid" },
  { title: "Transformers", year: 2007, tier: "mid" },
  { title: "Knocked Up", year: 2007, tier: "mid" },
  { title: "300", year: 2006, tier: "mid" },
  { title: "The Devil Wears Prada", year: 2006, tier: "mid" },
  { title: "The Pursuit of Happyness", year: 2006, tier: "mid" },
  { title: "V for Vendetta", year: 2005, tier: "mid" },
  { title: "War of the Worlds", year: 2005, tier: "mid" },
  { title: "Mr. & Mrs. Smith", year: 2005, tier: "mid" },
  { title: "Sin City", year: 2005, tier: "mid" },
  { title: "The Notebook", year: 2004, tier: "mid" },
  { title: "Mean Girls", year: 2004, tier: "mid" },
  { title: "Anchorman", year: 2004, tier: "mid" },
  { title: "Troy", year: 2004, tier: "mid" },
  { title: "Spider-Man 2", year: 2004, tier: "mid" },
  { title: "Pirates of the Caribbean: The Curse of the Black Pearl", year: 2003, tier: "mid" },
  { title: "School of Rock", year: 2003, tier: "mid" },
  { title: "Spider-Man", year: 2002, tier: "mid" },
  { title: "The Bourne Identity", year: 2002, tier: "mid" },
  { title: "Ice Age", year: 2002, tier: "mid" },
  { title: "Ocean's Eleven", year: 2001, tier: "mid" },
  { title: "A Beautiful Mind", year: 2001, tier: "mid" },
  { title: "Donnie Darko", year: 2001, tier: "mid" },
  { title: "Cast Away", year: 2000, tier: "mid" },
  { title: "X-Men", year: 2000, tier: "mid" },
  { title: "Unbreakable", year: 2000, tier: "mid" },
  { title: "The Talented Mr. Ripley", year: 1999, tier: "mid" },
  { title: "The Blair Witch Project", year: 1999, tier: "mid" },
  { title: "Office Space", year: 1999, tier: "mid" },
  { title: "The Big Lebowski", year: 1998, tier: "mid" },
  { title: "Shakespeare in Love", year: 1998, tier: "mid" },
  { title: "Armageddon", year: 1998, tier: "mid" },
  { title: "Independence Day", year: 1996, tier: "mid" },
  { title: "The Rock", year: 1996, tier: "mid" },
  { title: "Twister", year: 1996, tier: "mid" },
  { title: "Mission: Impossible", year: 1996, tier: "mid" },
  { title: "Men in Black", year: 1997, tier: "mid" },
  { title: "Air Force One", year: 1997, tier: "mid" },
  { title: "Con Air", year: 1997, tier: "mid" },
  { title: "Deep Impact", year: 1998, tier: "mid" },
  { title: "The Mummy", year: 1999, tier: "mid" },
  { title: "Austin Powers: The Spy Who Shagged Me", year: 1999, tier: "mid" },
  { title: "The Waterboy", year: 1998, tier: "mid" },
  { title: "Enemy of the State", year: 1998, tier: "mid" },
  { title: "Starship Troopers", year: 1997, tier: "mid" },
  { title: "Batman Forever", year: 1995, tier: "mid" },
  { title: "Jumanji", year: 1995, tier: "mid" },
  { title: "The Mask", year: 1994, tier: "mid" },
  { title: "True Lies", year: 1994, tier: "mid" },
  { title: "Speed", year: 1994, tier: "mid" },
  { title: "Demolition Man", year: 1993, tier: "mid" },
  { title: "The Fugitive", year: 1993, tier: "mid" },
  { title: "Cliffhanger", year: 1993, tier: "mid" },
  { title: "Total Recall", year: 1990, tier: "mid" },
  { title: "Point Break", year: 1991, tier: "mid" },
  { title: "Robin Hood: Prince of Thieves", year: 1991, tier: "mid" },
  // Classics (1920s-1970s) — mid tier
  { title: "Ben-Hur", year: 1959, tier: "mid" },
  { title: "The Ten Commandments", year: 1956, tier: "mid" },
  { title: "Spartacus", year: 1960, tier: "mid" },
  { title: "The Great Escape", year: 1963, tier: "mid" },
  { title: "Planet of the Apes", year: 1968, tier: "mid" },
  { title: "Bullitt", year: 1968, tier: "mid" },
  { title: "The Dirty Dozen", year: 1967, tier: "mid" },
  { title: "Goldfinger", year: 1964, tier: "mid" },
  { title: "The Pink Panther", year: 1963, tier: "mid" },
  { title: "The Poseidon Adventure", year: 1972, tier: "mid" },
  { title: "The Towering Inferno", year: 1974, tier: "mid" },
  { title: "Dirty Harry", year: 1971, tier: "mid" },
  { title: "Willy Wonka and the Chocolate Factory", year: 1971, tier: "mid" },
  { title: "Grease", year: 1978, tier: "mid" },
  { title: "The Omen", year: 1976, tier: "mid" },
  { title: "Logan's Run", year: 1976, tier: "mid" },
  { title: "Westworld", year: 1973, tier: "mid" },
  { title: "The Longest Yard", year: 1974, tier: "mid" },

  // ===== LOW (expected 0-49) =====
  { title: "Cats", year: 2019, tier: "low" },
  { title: "Morbius", year: 2022, tier: "low" },
  { title: "Madame Web", year: 2024, tier: "low" },
  { title: "Batman v Superman: Dawn of Justice", year: 2016, tier: "low" },
  { title: "Suicide Squad", year: 2016, tier: "low" },
  { title: "X-Men: Apocalypse", year: 2016, tier: "low" },
  { title: "Transformers: Age of Extinction", year: 2014, tier: "low" },
  { title: "Transformers: Revenge of the Fallen", year: 2009, tier: "low" },
  { title: "The Emoji Movie", year: 2017, tier: "low" },
  { title: "Baywatch", year: 2017, tier: "low" },
  { title: "Dark Phoenix", year: 2019, tier: "low" },
  { title: "Artemis Fowl", year: 2020, tier: "low" },
  { title: "365 Days", year: 2020, tier: "low" },
  { title: "Hubie Halloween", year: 2020, tier: "low" },
  { title: "Thunder Force", year: 2021, tier: "low" },
  { title: "Pixels", year: 2015, tier: "low" },
  { title: "Norm of the North", year: 2016, tier: "low" },
  { title: "Amsterdam", year: 2022, tier: "low" },
  { title: "Moonfall", year: 2022, tier: "low" },
  { title: "Firestarter", year: 2022, tier: "low" },
  { title: "Deep Water", year: 2022, tier: "low" },
  { title: "Aquaman and the Lost Kingdom", year: 2023, tier: "low" },
  { title: "Ant-Man and the Wasp: Quantumania", year: 2023, tier: "low" },
  { title: "Shazam! Fury of the Gods", year: 2023, tier: "low" },
  { title: "Borderlands", year: 2024, tier: "low" },
  { title: "Horizon: An American Saga", year: 2024, tier: "low" },
  { title: "Winnie-the-Pooh: Blood and Honey", year: 2023, tier: "low" },
  { title: "Meg 2: The Trench", year: 2023, tier: "low" },
  { title: "Fast X", year: 2023, tier: "low" },
  { title: "Expend4bles", year: 2023, tier: "low" },
  { title: "The Nun II", year: 2023, tier: "low" },
  // New low entries
  { title: "Joker: Folie a Deux", year: 2024, tier: "low" },
  { title: "Kraven the Hunter", year: 2024, tier: "low" },
  { title: "Megalopolis", year: 2024, tier: "low" },
  { title: "The Crow", year: 2024, tier: "low" },
  { title: "Rebel Moon: Part One", year: 2023, tier: "low" },
  { title: "Rebel Moon: Part Two", year: 2024, tier: "low" },
  { title: "Plane", year: 2023, tier: "low" },
  { title: "Haunted Mansion", year: 2023, tier: "low" },
  { title: "The Marvels", year: 2023, tier: "low" },
  { title: "Blue Beetle", year: 2023, tier: "low" },
  { title: "65", year: 2023, tier: "low" },
  { title: "Renfield", year: 2023, tier: "low" },
  { title: "Knock at the Cabin", year: 2023, tier: "low" },
  { title: "Hypnotic", year: 2023, tier: "low" },
  { title: "Secret Invasion", year: 2023, tier: "low" },
  { title: "The Exorcist: Believer", year: 2023, tier: "low" },
  { title: "Five Nights at Freddy's", year: 2023, tier: "low" },
  { title: "Heart of Stone", year: 2023, tier: "low" },
  { title: "Extraction 2", year: 2023, tier: "low" },
  { title: "Infinity Pool", year: 2023, tier: "low" },
  { title: "Megan", year: 2023, tier: "low" },
  { title: "The Woman King", year: 2022, tier: "low" },
  { title: "Jurassic World Dominion", year: 2022, tier: "low" },
  { title: "Uncharted", year: 2022, tier: "low" },
  { title: "Memory", year: 2022, tier: "low" },
  { title: "The 355", year: 2022, tier: "low" },
  { title: "The King's Man", year: 2021, tier: "low" },
  { title: "Space Jam: A New Legacy", year: 2021, tier: "low" },
  { title: "Tom and Jerry", year: 2021, tier: "low" },
  { title: "Snake Eyes", year: 2021, tier: "low" },
  { title: "Mortal Kombat", year: 2021, tier: "low" },
  { title: "Old", year: 2021, tier: "low" },
  { title: "Infinite", year: 2021, tier: "low" },
  { title: "Monster Hunter", year: 2020, tier: "low" },
  { title: "Wonder Woman 1984", year: 2020, tier: "low" },
  { title: "Mulan", year: 2020, tier: "low" },
  { title: "The New Mutants", year: 2020, tier: "low" },
  { title: "Dolittle", year: 2020, tier: "low" },
  { title: "Fantasy Island", year: 2020, tier: "low" },
  { title: "Bloodshot", year: 2020, tier: "low" },
  { title: "The Grudge", year: 2020, tier: "low" },
  { title: "Scoob!", year: 2020, tier: "low" },
  { title: "Underwater", year: 2020, tier: "low" },
  { title: "Hellboy", year: 2019, tier: "low" },
  { title: "Rambo: Last Blood", year: 2019, tier: "low" },
  { title: "Terminator: Dark Fate", year: 2019, tier: "low" },
  { title: "Gemini Man", year: 2019, tier: "low" },
  { title: "The Addams Family", year: 2019, tier: "low" },
  { title: "Godzilla: King of the Monsters", year: 2019, tier: "low" },
  { title: "The Secret Life of Pets 2", year: 2019, tier: "low" },
  { title: "Playmobil: The Movie", year: 2019, tier: "low" },
  { title: "47 Meters Down: Uncaged", year: 2019, tier: "low" },
  { title: "Replicas", year: 2018, tier: "low" },
  { title: "Robin Hood", year: 2018, tier: "low" },
  { title: "The Predator", year: 2018, tier: "low" },
  { title: "Pacific Rim: Uprising", year: 2018, tier: "low" },
  { title: "The Meg", year: 2018, tier: "low" },
  { title: "Skyscraper", year: 2018, tier: "low" },
  { title: "Slender Man", year: 2018, tier: "low" },
  { title: "Winchester", year: 2018, tier: "low" },
  { title: "The Happytime Murders", year: 2018, tier: "low" },
  { title: "Geostorm", year: 2017, tier: "low" },
  { title: "Transformers: The Last Knight", year: 2017, tier: "low" },
  { title: "The Dark Tower", year: 2017, tier: "low" },
  { title: "Pirates of the Caribbean: Dead Men Tell No Tales", year: 2017, tier: "low" },
  { title: "Flatliners", year: 2017, tier: "low" },
  { title: "Rings", year: 2017, tier: "low" },
  { title: "King Arthur: Legend of the Sword", year: 2017, tier: "low" },
  { title: "Ghost in the Shell", year: 2017, tier: "low" },
  { title: "Power Rangers", year: 2017, tier: "low" },
  { title: "Independence Day: Resurgence", year: 2016, tier: "low" },
  { title: "Warcraft", year: 2016, tier: "low" },
  { title: "Gods of Egypt", year: 2016, tier: "low" },
  { title: "Ben-Hur", year: 2016, tier: "low" },
  { title: "Alice Through the Looking Glass", year: 2016, tier: "low" },
  { title: "Assassin's Creed", year: 2016, tier: "low" },
  { title: "Passengers", year: 2016, tier: "low" },
  { title: "The Divergent Series: Allegiant", year: 2016, tier: "low" },
  { title: "Fantastic Four", year: 2015, tier: "low" },
  { title: "Jupiter Ascending", year: 2015, tier: "low" },
  { title: "Pan", year: 2015, tier: "low" },
  { title: "The Hobbit: The Battle of the Five Armies", year: 2014, tier: "low" },
  { title: "Exodus: Gods and Kings", year: 2014, tier: "low" },
  { title: "Teenage Mutant Ninja Turtles", year: 2014, tier: "low" },
  { title: "Dracula Untold", year: 2014, tier: "low" },
  { title: "The Legend of Hercules", year: 2014, tier: "low" },
  { title: "Transcendence", year: 2014, tier: "low" },
  { title: "After Earth", year: 2013, tier: "low" },
  { title: "Movie 43", year: 2013, tier: "low" },
  { title: "Grown Ups 2", year: 2013, tier: "low" },
  { title: "The Lone Ranger", year: 2013, tier: "low" },
  { title: "R.I.P.D.", year: 2013, tier: "low" },
  { title: "A Good Day to Die Hard", year: 2013, tier: "low" },
  { title: "Battleship", year: 2012, tier: "low" },
  { title: "Total Recall", year: 2012, tier: "low" },
  { title: "Wrath of the Titans", year: 2012, tier: "low" },
  { title: "Ghost Rider: Spirit of Vengeance", year: 2012, tier: "low" },
  { title: "Jack and Jill", year: 2011, tier: "low" },
  { title: "Green Lantern", year: 2011, tier: "low" },
  { title: "Sucker Punch", year: 2011, tier: "low" },
  { title: "Conan the Barbarian", year: 2011, tier: "low" },
  { title: "The Smurfs", year: 2011, tier: "low" },
  { title: "Bucky Larson: Born to Be a Star", year: 2011, tier: "low" },
  { title: "The Last Airbender", year: 2010, tier: "low" },
  { title: "Clash of the Titans", year: 2010, tier: "low" },
  { title: "Jonah Hex", year: 2010, tier: "low" },
  { title: "Killers", year: 2010, tier: "low" },
  { title: "Gulliver's Travels", year: 2010, tier: "low" },
  { title: "Vampires Suck", year: 2010, tier: "low" },
  { title: "Dragonball Evolution", year: 2009, tier: "low" },
  { title: "X-Men Origins: Wolverine", year: 2009, tier: "low" },
  { title: "G.I. Joe: The Rise of Cobra", year: 2009, tier: "low" },
  { title: "All About Steve", year: 2009, tier: "low" },
  { title: "Old Dogs", year: 2009, tier: "low" },
  { title: "The Happening", year: 2008, tier: "low" },
  { title: "The Love Guru", year: 2008, tier: "low" },
  { title: "Meet the Spartans", year: 2008, tier: "low" },
  { title: "Disaster Movie", year: 2008, tier: "low" },
  { title: "The Hottie and the Nottie", year: 2008, tier: "low" },
  { title: "Speed Racer", year: 2008, tier: "low" },
  { title: "Spider-Man 3", year: 2007, tier: "low" },
  { title: "Ghost Rider", year: 2007, tier: "low" },
  { title: "Epic Movie", year: 2007, tier: "low" },
  { title: "Norbit", year: 2007, tier: "low" },
  { title: "Catwoman", year: 2004, tier: "low" },
  { title: "Gigli", year: 2003, tier: "low" },
  { title: "From Justin to Kelly", year: 2003, tier: "low" },
  { title: "Battlefield Earth", year: 2000, tier: "low" },
  { title: "Freddy Got Fingered", year: 2001, tier: "low" },
  { title: "Glitter", year: 2001, tier: "low" },
  { title: "Alone in the Dark", year: 2005, tier: "low" },
  { title: "Son of the Mask", year: 2005, tier: "low" },
  { title: "Deuce Bigalow: European Gigolo", year: 2005, tier: "low" },
  { title: "The Wicker Man", year: 2006, tier: "low" },
  { title: "BloodRayne", year: 2005, tier: "low" },
  { title: "House of the Dead", year: 2003, tier: "low" },
  { title: "Fifty Shades of Grey", year: 2015, tier: "low" },
  { title: "Fifty Shades Darker", year: 2017, tier: "low" },
  { title: "The Snowman", year: 2017, tier: "low" },
  { title: "The Turning", year: 2020, tier: "low" },
  { title: "Color Out of Space", year: 2019, tier: "low" },
  { title: "Serenity", year: 2019, tier: "low" },
  { title: "The Fanatic", year: 2019, tier: "low" },
  { title: "Music", year: 2021, tier: "low" },
  { title: "Diana the Musical", year: 2021, tier: "low" },
  { title: "The Matrix Resurrections", year: 2021, tier: "low" },
  { title: "Moonshot", year: 2022, tier: "low" },
  { title: "Blacklight", year: 2022, tier: "low" },
  { title: "Samaritan", year: 2022, tier: "low" },
  { title: "Batman and Robin", year: 1997, tier: "low" },
  { title: "Wild Wild West", year: 1999, tier: "low" },
  { title: "The Avengers", year: 1998, tier: "low" },
  { title: "Speed 2: Cruise Control", year: 1997, tier: "low" },
  { title: "Lost in Space", year: 1998, tier: "low" },
  { title: "Godzilla", year: 1998, tier: "low" },
  { title: "Mortal Kombat: Annihilation", year: 1997, tier: "low" },
  { title: "Spice World", year: 1997, tier: "low" },
  { title: "Jaws: The Revenge", year: 1987, tier: "low" },
  { title: "Superman IV: The Quest for Peace", year: 1987, tier: "low" },
  { title: "Howard the Duck", year: 1986, tier: "low" },
  { title: "Jingle All the Way", year: 1996, tier: "low" },
  { title: "Anaconda", year: 1997, tier: "low" },
  { title: "The Flintstones", year: 1994, tier: "low" },
  { title: "Kazaam", year: 1996, tier: "low" },
  { title: "Judge Dredd", year: 1995, tier: "low" },
  { title: "Showgirls", year: 1995, tier: "low" },
  { title: "Waterworld", year: 1995, tier: "low" },
  { title: "Lara Croft: Tomb Raider", year: 2001, tier: "low" },
  { title: "Pearl Harbor", year: 2001, tier: "low" },
  { title: "Rollerball", year: 2002, tier: "low" },
  { title: "Daredevil", year: 2003, tier: "low" },
  { title: "Hulk", year: 2003, tier: "low" },
  { title: "The League of Extraordinary Gentlemen", year: 2003, tier: "low" },
  { title: "Elektra", year: 2005, tier: "low" },
  { title: "Fantastic Four", year: 2005, tier: "low" },
  { title: "Stealth", year: 2005, tier: "low" },
  { title: "Ultraviolet", year: 2006, tier: "low" },
  { title: "Eragon", year: 2006, tier: "low" },
  { title: "The Covenant", year: 2006, tier: "low" },
  { title: "Resident Evil: Extinction", year: 2007, tier: "low" },
  // Classics (1920s-1970s) — low tier
  { title: "Plan 9 from Outer Space", year: 1957, tier: "low" },
  { title: "Robot Monster", year: 1953, tier: "low" },
  { title: "Santa Claus Conquers the Martians", year: 1964, tier: "low" },
  { title: "Manos: The Hands of Fate", year: 1966, tier: "low" },
  { title: "The Terror of Tiny Town", year: 1938, tier: "low" },
  { title: "Glen or Glenda", year: 1953, tier: "low" },
  { title: "The Beast of Yucca Flats", year: 1961, tier: "low" },
  { title: "The Creeping Terror", year: 1964, tier: "low" },
  { title: "Eegah", year: 1962, tier: "low" },
  { title: "The Giant Claw", year: 1957, tier: "low" },
  { title: "Attack of the Killer Tomatoes", year: 1978, tier: "low" },
  { title: "Sgt. Pepper's Lonely Hearts Club Band", year: 1978, tier: "low" },
  { title: "The Swarm", year: 1978, tier: "low" },
  { title: "Orca", year: 1977, tier: "low" },
  { title: "Exorcist II: The Heretic", year: 1977, tier: "low" },
  { title: "The Island of Dr. Moreau", year: 1977, tier: "low" },
  { title: "Earthquake", year: 1974, tier: "low" },
  { title: "Zardoz", year: 1974, tier: "low" },
];

export const BUCKET_SIZE = 8;
export const TARGET = 404;

// Per-bucket tier distribution: 3 high, 3 mid, 2 low
export const TIER_MIX: { tier: Tier; count: number }[] = [
  { tier: "high", count: 3 },
  { tier: "mid", count: 3 },
  { tier: "low", count: 2 },
];
